# Generated by Django 4.2.13 on 2024-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.CharField(default='', max_length=550, verbose_name='Адреса/Місце проведення')),
                ('latitude', models.CharField(blank=True, default='', max_length=250, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, default='', max_length=250, verbose_name='longitude')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
