# Generated by Django 4.2.13 on 2024-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('workshop', 'Workshop'), ('webinar', 'Webinar')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
